/*-----UC1-----*/

CREATE DATABASE AddressBook;
use AddressBook;

/*-----UC2----*/

create table Address_Book (
	ID int IDENTITY(1,1) PRIMARY KEY (ID),
	FIRSTNAME varchar(50),
	LASTNAME varchar(50),
	ADDRESSs varchar(100),
	CITY varchar(50),
	STATE varchar(50),
	ZIP varchar(6),
	PHONENO varchar(12),
	EMAIL varchar(50));

	SELECT * FROM Address_Book;

/*------UC3-----*/
INSERT INTO Address_Book(FirstName,LastName,Addresss,City,State,Zip,PhoneNo,Email) VALUES
 ('AARNA','NAMALA','5/89,BENZCIRCLE','VIJAYAWADA','ANDHRAPRADESH',521345,8866485766,'aarna@gmail.com');

SELECT * FROM Address_Book;

INSERT INTO Address_Book VALUES('VIJAYA','TALLURI','6/72,PARAWADA','VIZAG','ANDHRA PRADESH',530045,9553945608,'vijaya@gmail.com');
INSERT INTO Address_Book VALUES('HARSHA','TALLURI','5/83,PEDATUMMIDI','BANTUMILLI','ANDHRA PRADESH',521329,9291261316,'harsha@gmail.com');

/*------UC4-----*/
SELECT * FROM Address_Book WHERE FIRSTNAME = 'VIJAYA';
UPDATE Address_Book SET State = 'TELANGANA' WHERE FIRSTNAME = 'VIJAYA';

/*------UC5-----*/
DELETE FROM ADDRESS_BOOK WHERE FIRSTNAME = 'VIJAYA';

/*------UC6-----*/
SELECT * FROM Address_Book WHERE City = 'VIZAG';
SELECT * FROM Address_Book WHERE State = 'ANDHRA PRADESH';

/*----UC7-----*/
SELECT COUNT(*) FROM Address_Book WHERE State = 'ANDHRA PRADESH';
SELECT COUNT(*) FROM Address_Book WHERE City = 'BANTUMILLI';

/*----UC8-----*/
SELECT * FROM Address_Book ORDER BY FIRSTNAME;

/*----UC9-----*/
ALTER TABLE Address_Book ADD Type VARCHAR(20);

UPDATE Address_Book SET Type='Friends' WHERE FirstName = 'AARNA';

UPDATE Address_Book SET Type='Family' WHERE FirstName = 'HARSHA' OR LASTNAME = 'TALLURI'

SELECT *FROM Address_Book;

/*----UC10-----*/
SELECT COUNT(*) FROM Address_Book WHERE Type='Family';

/*----UC11-----*/
INSERT INTO ADDRESS_BOOK VALUES('JYOTHI','NAMALA','6/72','SINDHANUR','KARNATAKA',521329,9667854303,'jyothi@gmail.com','Friends')
INSERT INTO ADDRESS_BOOK VALUES('SHYAM','KALLA','7/45','KUKATPALLI','HYDERABAD',50045,8765342987,'shyam@gmail.com','Friends')
INSERT INTO ADDRESS_BOOK VALUES('SITA','KATTI','7/89','MADHUARAWADA','ANDHRAPRADESH',521329,8996754306,'sita@gmail.com','Family')
INSERT INTO ADDRESS_BOOK VALUES('RAMESH','DUNDIGALA','8/95','NAMPALLY','HYDERABAD',50059,9765845606,'ramesh@gmail.com','Family')


SELECT *FROM Address_Book;

/*----UC12------*/

CREATE TABLE CONTACT_TYPE(
TYPE_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
TYPE_NAME VARCHAR(25) NOT NULL)

INSERT INTO CONTACT_TYPE VALUES('Family'),('Friends'),('Colleagues')
SELECT * FROM CONTACT_TYPE


CREATE TABLE CONTACT_ADDRESS(
CONTACT_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
FIRST_NAME VARCHAR(25) NOT NULL,
LAST_NAME VARCHAR(25) NOT NULL,
ADDRESS VARCHAR(100) NOT NULL,
CITY VARCHAR(25) NOT NULL,
STATE VARCHAR(25) NOT NULL,
ZIP_CODE FLOAT NOT NULL,
EMAIL VARCHAR(50) NOT NULL,
TYPE_ID INT NOT NULL)

SELECT * FROM CONTACT_ADDRESS

INSERT INTO CONTACT_ADDRESS VALUES('Lakshmi','Talluri','6/72','Hyderabad','Telanga',530045,'lakshmi@gmail.com',1)
INSERT INTO CONTACT_ADDRESS VALUES('Vijaya','Manne','6/89','Vijayawada','Andhra pradesh',521329,'vijaya@gmail.com',2)
INSERT INTO CONTACT_ADDRESS VALUES('Sita','Kalla','9/86','Vizag','Andhra Pradesh',594521,'sita@gmail.com',2)
INSERT INTO CONTACT_ADDRESS VALUES('Tarun','Namala','9/76','Sinhanur','Karnataka',665438,'tarun@gmail.com',1)
INSERT INTO CONTACT_ADDRESS VALUES('Ramesh','Dundigala','6/89','Chennai','Tamil Nadu',986321,'ramesh@gmail.com',3)
INSERT INTO CONTACT_ADDRESS VALUES('Harsha','Sridarvalli','8/54','Ongole','Andhra Pradesh',524321,'harsha@gmail.com',2)
INSERT INTO CONTACT_ADDRESS VALUES('Radha','saragadam','6/72','Coimbatore','Tamil Nadu',532187,'radha@gmail.com',1)

SELECT * FROM CONTACT_ADDRESS


CREATE TABLE CONTACT_PHONE(
CONTACT_ID INT NOT NULL,
FIRST_NAME VARCHAR(25) NOT NULL,
PHONE_1 FLOAT NOT NULL,
PHONE_2 FLOAT NULL)

INSERT INTO CONTACT_PHONE VALUES(1,'Lakshmi',9291261319,7554865303)
INSERT INTO CONTACT_PHONE VALUES(3,'Ramesh',7890123456,7689054321)
INSERT INTO CONTACT_PHONE VALUES(4,'Sita',6543217890,8906745123)
INSERT INTO CONTACT_PHONE VALUES(5,'Harsha',9907564231,7908645231)
INSERT INTO CONTACT_PHONE (CONTACT_ID,FIRST_NAME,PHONE_1) VALUES(6,'Aarna',6789054123)
INSERT INTO CONTACT_PHONE VALUES(7,'Lakshmi',7890654321,6795321405)
INSERT INTO CONTACT_PHONE VALUES(8,'Radha',9786672345,8755428901)

SELECT * FROM CONTACT_PHONE


ALTER TABLE CONTACT_ADDRESS ADD CONSTRAINT FK_CONTACT_TYPE FOREIGN KEY(TYPE_ID) REFERENCES CONTACT_TYPE(TYPE_ID) ON DELETE CASCADE ON UPDATE CASCADE
ALTER TABLE CONTACT_PHONE ADD CONSTRAINT FK_CONTACT_PHONE FOREIGN KEY(CONTACT_ID) REFERENCES CONTACT_ADDRESS(CONTACT_ID) ON DELETE CASCADE ON UPDATE CASCADE

------UC13----- UC6, UC7, UC8, UC10

SELECT * FROM CONTACT_ADDRESS WHERE City = 'Hyderabad'
SELECT * FROM CONTACT_ADDRESS WHERE STATE = 'ANDHRA PRADESH'

SELECT CITY, COUNT(CITY) AS CONTACT_ADDRESS FROM ADDRESS_BOOK GROUP BY CITY
SELECT STATE, COUNT(STATE) AS CONTACT_ADDRESS FROM ADDRESS_BOOK GROUP BY STATE

SELECT * FROM CONTACT_ADDRESS WHERE CITY = 'Vizag' ORDER BY FIRST_NAME

SELECT TYPE_NAME,COUNT(TYPE_NAME) FROM CONTACT_TYPE CT INNER JOIN CONTACT_ADDRESS CA ON CT.TYPE_ID = CA.TYPE_ID GROUP BY TYPE_NAME
SELECT TYPE_NAME,CA.FIRST_NAME,PHONE_1 FROM CONTACT_TYPE CT INNER JOIN CONTACT_ADDRESS CA ON CT.TYPE_ID = CA.TYPE_ID INNER JOIN CONTACT_PHONE CP ON CA.CONTACT_ID = CP.CONTACT_ID


